MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_209a011.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a032.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a022.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_184a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_122337.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_194a022.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080720/ICE_20080720_121213.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2013_dtag/oo13_068a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-071009.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07e.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a111.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07i.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_182a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07P.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a013.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-12-07o.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-12-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a113.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-05-07J.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a007.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080708/ICE_20080708_131902.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a102.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a012.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-11-07m.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-21-07d.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a009.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b014.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a012.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T350.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a104.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_166a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_horizontal_array/220623_0001_3.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-26-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a014.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-071003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-15-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a102.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a014.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_143233.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07g.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b013.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-071001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-13-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a015.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-05-07F.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T338.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080709/ICE_20080709_145256.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2013_dtag/oo13_071a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-18-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a117.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-071005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-21-07f.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080709/ICE_20080709_143015.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_186a006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080717/ICE_20080717_123835.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-23-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-16-07G.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T339.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_123337.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07K.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a009.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-071008.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a033.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_182a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07f.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b018.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-071003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-071002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a021.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_182a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a019.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a041.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2013_dtag/oo13_071a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2013_dtag/oo13_072a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a101.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a042.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-17-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-21-07T304.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-07T328.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-15-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b020.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_166a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b011.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a011.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a008.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_201a011.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a105.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_121337.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-12-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b019.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a109.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-11-07l.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T313.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-07-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_209a013.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_202b006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a007.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-12-07B.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a015.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_201a012.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_131338.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a022.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080716/ICE_20080716_150952.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a114.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a107.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a106.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a108.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-18-07g.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-22-071004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07G.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a014.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_133233.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a098.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a013.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080709/ICE_20080709_132106.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_188a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a011.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T318.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a024.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-23-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a105.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_171a005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b022.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07h.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-07T298.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_186a007.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a008.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T317.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-26-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a108.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07d.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080720/ICE_20080720_092718.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a024.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_228a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080708/ICE_20080708_140813.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-11-07h.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-26-07d.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T363.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-07-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080708/ICE_20080708_141813.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080709/ICE_20080709_133106.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a043.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T340.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07N.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015_07_14b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T315.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_134233.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a011.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080708/ICE_20080708_134813.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080720/ICE_20080720_095719.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07O.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_209a012.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-05-07E.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-17-07d.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_166a005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080716/ICE_20080716_154757.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080720/ICE_20080720_104734.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a116.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a112.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_194a012.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_186a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a012.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-15-07f.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_184a019.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a014.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_194a014.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a104.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_202b005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-13-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080717/ICE_20080717_122834.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_202b003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080709/ICE_20080709_144015.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a010.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T349.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a031.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-12-07n.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a023.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a010.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a018.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_202b004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-09-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a015.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-071012.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-15-07g.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-16-07I.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-16-07H.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a010.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T341.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_horizontal_array/220623_0002_3.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_194a023.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2013_dtag/oo13_072a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-09-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080709/ICE_20080709_134107.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T347.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07D.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a095.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-12-07C.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2013_dtag/oo13_072a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-21-07g.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-21-07T302.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_194a011.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a098.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-07T299.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-11-07k.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_184a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-21-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_166a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a099.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-05-07H.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_201a013.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a110.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a023.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_228a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07A.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_186a008.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080708/ICE_20080708_143813.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a016.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080717/ICE_20080717_124835.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-12-07l.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080708/ICE_20080708_142813.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T333.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b017.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T322.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-13-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_194a024.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-18-07f.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080720/ICE_20080720_114841.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080709/ICE_20080709_151004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a009.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a115.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_182a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_186a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-07-07A.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080716/ICE_20080716_171246.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T331.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a095.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T345.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-22-071002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-12-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-09-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_184a005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b016.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080720/ICE_20080720_094719.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_184a018.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080709/ICE_20080709_153449.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a010.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_horizontal_array/220623_0005_3.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a109.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T351.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_171a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a107.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-071004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T342.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_201a014.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a094.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-07T323.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_171a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a009.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-16-07E.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_115223.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_135233.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b021.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-16-07D.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-22-071005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-071001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_171a006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T321.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-07-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a092.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a111.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-16-07A.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-17-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-07-29a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_184a020.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-15-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a008.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T352.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_186a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T343.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-071007.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-07T297.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-071011.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_194a013.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-18-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_228a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b012.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T320.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-07-07C.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_228a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07b.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-21-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-15-07e.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-26-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a013.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-071006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b015.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-15-07d.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T319.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-12-07A.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_horizontal_array/220623_0006_3.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a103.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a020.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-07T296.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_horizontal_array/220623_0003_3.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a007.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_171a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-22-071006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a110.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-20-071010.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_189a025.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-17-07a.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-071004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_183a006.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-11-07i.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_186a005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a009.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_194a021.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a008.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a093.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07I.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-21-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_201a021.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T353.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T344.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_171a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-16-07F.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_166a001.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T337.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-11-07j.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a096.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-07-07B.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2008-summer/20080718/ICE_20080718_114223.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-05-07C.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181a096.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_184a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-22-071007.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_181b023.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-17-07h.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T348.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-25-07T332.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a010.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07C.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-13-07B.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2023_dtag/oo23_188a094.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_228a005.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-07-29c.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2013_dtag/oo13_071a003.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-18-07d.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-09-07i.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a007.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_186a004.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_175a002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2021_dtag/oo21_199a019.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-05-07D.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-27-07T346.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2009_dtag/oo09_200a034.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_195a008.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_dtag/oo22_170a008.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-24-071002.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-25-07j.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2015_towed_array/2015-12-07e.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-23-07T314.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2022_horizontal_array/220623_0004_3.wav
MakeData/create_spectrogram.py  -c euler -p /Users/sb/polybox/Documents/Research/Sebastian/OrcAI_project/ -w /Volumes/OrcAI-Disk/Acoustics/2016_towed_array/2016-16-07C.wav
